/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  modulesSidebar: [{type: 'autogenerated', dirName: '.'}],
  toolkitSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;