name: CI

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Placeholder step
      run: echo "This is an empty workflow"